# AUTOGENERATED! DO NOT EDIT! File to edit: ../io.ipynb.

# %% auto #0
__all__ = ['imread', 'load_pts']

# %% ../io.ipynb #0f1da1d7
import cv2
import numpy as np
import os
def imread(path):
    return cv2.cvtColor(cv2.imread(path), cv2.COLOR_BGR2RGB)

def load_pts(fname):
    if os.path.isfile(fname):
        arr = np.loadtxt(fname)
        assert arr.shape[1] == 4
        return arr
    return np.empty((0,4))
